### ISSUE TITLE
Sandwine does not honor $WINEPREFIX

### ISSUE THREAD

**Issue by cadrian** [hartwork/sandwine#66]
Hi,

I use several parallel wine installations. To do that, I use the WINEPREFIX environment variable. It seems not to be used by sandwine. Is there an alternative?

Thanks

**Comment by hartwork** [comment]
Hi @cadrian, did you see…

```console
# sandwine --help | grep -C1 dotwine
mount arguments:
  --dotwine PATH:{ro,rw}
                        use PATH for ~/.wine/ (default: use tmpfs, empty and non-persistent)
```

… ? That's the safe version of `WINEPREFIX` in that there will be no surprises.

What do you think?

**Comment by cadrian** [comment]
Hi @hartwork, OK, I missed that one.

I don't see how there could be any surprise with that well-known variable, but there surely is something I overlooked. In my case, I'll just pass `--dotwine "$WINEPREFIX":rw` though :-)

It works- but it has its own problems, related to `--network`. I'll open a specific ticket for that one.

Thanks!

**Comment by hartwork** [comment]
> I don't see how there could be any surprise with that well-known variable, but there surely is something I overlooked.

@cadrian maybe there's an optimistic and a pessimistic take on this. I'm taking a pessimistic view here in that auto-adding th path in `${WINEPREFIX}` means that the user needs to be aware of its current value at all times. Right now that feels like expecting to me from the user to me. I can sleep over it.
