### ISSUE TITLE
Using 'sandwine' with chroot

### ISSUE THREAD

**Issue by mabra** [hartwork/sandwine#83]
Find this tool interesting, but there seems not to be a way or instructions
to use it with a chroot (where wine has been installed). Without using
a chroot for wine, the host has to get "a messy repository" with the
32bit libs/apps, what I want to avoid (using debian currently).
Is it possible?

**Comment by hartwork** [comment]
@mabra it should be possible to use sandwine from within a chroot already, but I'm not sure I understand what for. Just enter the chroot, install sandwine inside, run sandwine, done. No? More details about your use case are welcome.

**Comment by hartwork** [comment]
@mabra I had a chance to sleep over this now. I'm coming to the conclusion that keeping the host free of the i386 architecture alone is not a strong enough motivation for me to to add explicit support for chroots to sandwine and the increase in complexity an special-casing that comes with it — not in my spare time. Thanks for your understanding.
